package de.iksgmbh.dbschemacomp.helper;

import static org.junit.Assert.fail;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

import de.iksgmbh.dbschemacomp.TestUtil;
import de.iksgmbh.dbschemacomp.domain.SchemaMetaData;

/**
 * Most basic Unit tests in this package!
 * 
 * @author Reik Oberrath
 */
public class SchemaParserTest 
{
	@Test
	public void parsesSimpleSchemaWithWhiteSpaces() 
	{
		// arrange
		String schema = " CREATE  TABLE table_name " + System.getProperty("line.separator")
				        + " ( column1  datatype1  ,  "
				        + "   column2	datatype2 ) ";
		
		// act
		SchemaMetaData result = SchemaParser.doYourJob(schema);
		
		// assert
		assertNotNull(result);
		assertEquals(1, result.getTableNumber(), "Number of Tables");
		assertEquals(2, result.getTable(1).getColumnNumber(), "Number of Columns");
		assertEquals("column1", result.getTable(1).getColumn(1).getColumnName().getValue(), "Column Name");
		assertEquals("datatype1", result.getTable(1).getColumn(1).getColumnType().getValue(), "Column Type");
		assertEquals("column2", result.getTable(1).getColumn(2).getColumnName().getValue(), "Column Name");
		assertEquals("datatype2", result.getTable(1).getColumn(2).getColumnType().getValue(), "Column Type");
	}

	@Test
	public void parsesSchemaWithTwoTables() 
	{
		// arrange
		String schema = "CREATE TABLE table1 (column11 datatype11, column12 datatype12, column13 datatype13);"
				      + "create table table2 (column21 datatype21);";
		
		// act
		SchemaMetaData result = SchemaParser.doYourJob(schema);
		
		// assert
		assertNotNull(result);
		assertEquals(2, result.getTableNumber(), "Number of Tables");
		assertEquals(3, result.getTable(1).getColumnNumber(), "Number of Columns");
		assertEquals(1, result.getTable(2).getColumnNumber(), "Number of Columns");
		assertEquals("column12", result.getTable(1).getColumn(2).getColumnName().getValue(), "Column Name");
		assertEquals("datatype12", result.getTable(1).getColumn(2).getColumnType().getValue(), "Column Type");
		assertEquals("column21", result.getTable(2).getColumn(1).getColumnName().getValue(), "Column Name");
		assertEquals("datatype21", result.getTable(2).getColumn(1).getColumnType().getValue(), "Column Type");
	}
	
	@Test
	public void parsesSchemaWithNotNullColumn() 
	{	
		// arrange
		String schema = "CREATE TABLE table1 (column1 varchar null,"
				                           + "column2 varchar not null,"
				                           + "column3 varchar);";
		
		// act
		SchemaMetaData result = SchemaParser.doYourJob(schema);
		
		// assert
		assertEquals(true, result.getTable(1).getColumn(1).isNullable(), "is column nullable");
		assertEquals(false, result.getTable(1).getColumn(2).isNullable(), "is column nullable");
		assertEquals(true, result.getTable(1).getColumn(3).isNullable(), "is column nullable");
	}
	
	@Test
	public void throwsExceptionForInvalidNullableState() 
	{
		// arrange
		String schema = "CREATE TABLE table (column1 datatype nullable);";
	
		try {
			// act
			SchemaParser.doYourJob(schema);
			fail("Expected exception not thrown!");
		} catch (Exception e) {
			// assert
			assertEquals("Invalid column definition: (column1 datatype nullable)", 
					     e.getMessage(), "Error Message");
		}
	
	}
	

	@Test
	public void parsesSchemaWithDefaultValue() 
	{	
		// arrange
		String schema = "CREATE TABLE table1 (column1 varchar default value,"
				                           + "column2 varchar);";
		
		// act
		SchemaMetaData result = SchemaParser.doYourJob(schema);
		
		// assert
		assertEquals("value", result.getTable(1).getColumn(1).getDefault(), "Default Value");
		assertEquals(null, result.getTable(1).getColumn(2).getDefault(), "Default Value");
	}
	
	@Test
	public void parsesSchemaWithNotNullAndDefaultValue() 
	{	
		// arrange
		String schema = "CREATE TABLE table1 (column1 varchar default value not null);";
		
		// act
		SchemaMetaData result = SchemaParser.doYourJob(schema);
		
		// assert
		assertEquals("value", result.getTable(1).getColumn(1).getDefault(), "Default Value");
		assertEquals(false, result.getTable(1).getColumn(1).isNullable(), "is column nullable");
	}
		
	@Test
	public void parsesSchemaWithGenerationInfo() 
	{	
		// arrange
		String schema = "CREATE TABLE tablename (ID int generated by default as identity, INFO varchar);";
		
		// act
		SchemaMetaData result = SchemaParser.doYourJob(schema);
		
		// assert
		assertEquals("generated by default as identity", result.getTable(1).getColumn(1).getGenerationInfo(), "Generation Info");
		assertEquals(null, result.getTable(1).getColumn(2).getGenerationInfo(), "Generation Info");
	}
	
	@Test
	public void parsesSchemaWithPrimaryKey() 
	{
		// arrange
		String schema = " CREATE  TABLE table_name " + System.getProperty("line.separator")
				        + " (column1 datatype1,  "
				        + "  column2 datatype2, primary key (column1));";
		
		// act
		SchemaMetaData result = SchemaParser.doYourJob(schema);
		
		// assert
		assertEquals("(column1)", result.getTable(1).getPrimaryKey(), "Primary Key");
	}
	
	@Test
	public void parsesSchemaWithUniqueConstraint() 
	{
		// arrange
		String schema = "create table aTable (aColumn aColumnType);"
				      + "alter table aTable add constraint anId unique (aColumn);";
		
		// act
		SchemaMetaData result = SchemaParser.doYourJob(schema);
		
		// assert
		assertEquals("alter table aTable add constraint anId unique (aColumn)", 
				     result.getTable(1).getUniqueConstraintStatement(), "Unique Columns");
	}
	
	@Test
	public void throwsExceptionForUnknownTable() 
	{
		// arrange
		String schema = "alter table aTable add constraint anId unique (aColumn);";
		
		try {
			// act
			SchemaParser.doYourJob(schema);
			fail("Expected exception not thrown!");
		} catch (Exception e) {
			// assert
			assertEquals("Unknown Table in Alter-Statement: "
					     + "alter table aTable add constraint anId unique (aColumn)", 
					     e.getMessage(), "Error Message");
		}
	}
	
	@Test
	public void throwsExceptionForUnknownColumn() 
	{
		// arrange
		String schema = "create table aTable (Column1 aColumnType);"
			           + "alter table aTable add constraint anId unique (Column2);";
		try {
			// act
			SchemaParser.doYourJob(schema);
			fail("Expected exception not thrown!");
		} catch (Exception e) {
			// assert
			assertEquals("Unknown column 'Column2' in Alter-Statement for table 'aTable'.", 
					     e.getMessage(), "Error Message");
		}
	}	
	
	@Test
	public void parsesH2Schema() 
	{
		// arrange
		String schema = TestUtil.readSchema("src/test/resources/H2DbSchema.txt");
		//System.err.println(schema);
		
		// act
		SchemaMetaData result = SchemaParser.doYourJob(schema);
		
		// assert
		assertEquals(6, result.getTableNumber(), "Number of Tables");
		assertEquals("(CREATION_DATE)", result.getTable(1).getPrimaryKey(), "Primary Key");
		assertEquals("generated by default as identity", result.getTable(2).getColumn(1).getGenerationInfo(), "Generation Info");
		assertEquals(true, result.getTable(3).getColumn(2).isNullable(), "is column nullable");
		assertEquals(null, result.getTable(4).getColumn(1).getGenerationInfo(), "Generation Info");
		assertEquals(null, result.getTable(4).getColumn(1).getDefault(), "Default Value");
		assertEquals("alter table USER add constraint UK_a65g3fmtvdwj8ro965b14fnko unique (NAME)", 
				     result.getTable(5).getUniqueConstraintStatement(), "Unique Constraint Statement");
		assertEquals(false, result.getTable(6).getColumn(1).isNullable(), "is column nullable");
		assertEquals(4, result.getTable(6).getColumnNumber(), "Number of Columns");
	}

}
